### ISSUE TITLE
Definition jumps are not possible with files containing Japanese characters.

### ISSUE THREAD

**Issue by rokudone** [Shopify/ruby-lsp#1347] opened 2024-02-03 11:34 UTC
### Ruby version

3.1.4, 3.2.2, 3.3.0

### Code snippet

Gemfile
```
# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'debug', platforms: %i[mri windows]
gem 'rubocop'
gem 'ruby-lsp'
```

vscode/settings.json
```
{
  "[ruby]": {
    "editor.defaultFormatter": "Shopify.ruby-lsp",
    "editor.formatOnSave": true,
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.semanticHighlighting.enabled": true,
    "editor.formatOnType": true
  },
  "rubyLsp.rubyVersionManager": "rbenv",
  "rubyLsp.formatter": "rubocop",
  "rubyLsp.enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true
  }
}
```

success file
```ruby
# frozen_string_literal: true

# Test Class
class Test
  TEST = 'test'

  def method1
    # test
    pp TEST
  end
end
```

failed file
```ruby
# frozen_string_literal: true

# Test Class
class Test
  TEST = 'test'

  def method1
    # テスト
    pp TEST
  end
end
```

success file 2
```ruby
# frozen_string_literal: true

# Test Class
class Test
  TEST = 'test'

  def method1
    pp TEST
    # テスト
  end
end
```

VSCode
```
Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621
```
However, I have the same issue on my Mac

### Description

I was going to use vscode's ruby-lsp plugin. However, after struggling for a while, I could not make the definition jump.
The cause seems to be the presence of Japanese comments in the file.

In the attached Ruby code, I assume a situation like jumping from `pp TEST` to `TEST = 'test'`.' In the case of the code written in `success file 1', it succeeds. But for the code in `failed file`, it fails. The only difference is that the Japanese comment `# テスト` is on the line above the jump source.

Furthermore, if you look at `success file 2`, it succeeds if the same Japanese comment is added to the line below the jump source.

If there is any information I am missing, please let me know.

![●-test rb-temp-_WSL_-Ubuntu-22 04_-Visual-Studio-Code-2024-02-03-20-28-01](https://github.com/Shopify/ruby-lsp/assets/136144987/a41d3f32-f69e-452d-8f2c-c68e0a91ea1c)

### Expected output

Maybe this is true for other languages as well. I hope that eventually Japanese will be handled properly and we can jump from `pp TEST` to `TEST = 'test'` in examples like `failed file`.

**Comment by rokudone** [comment] 2024-02-06 10:07
Thanks for getting back to me. I could not find that Issue. Sorry to have bothered you.

It seems like a difficult issue to solve. I will wait patiently.

I look forward to having a great product available again. I wish you the best of luck!

**Comment by yamatowani** [comment] 2024-09-21 07:00
I have a similar problem, How is your progress?

### Description
I'm also using VSCode's ruby-lsp plugin, but it seems that if there is more than 13 bytes of character data, including multibyte characters, in the method comment, I cannot define a jump.
Specifically, it is not possible to jump from the following`foobar` instances to the definition source.

| Case | Data Quantity | Result |
|--------|--------|--------|
| "あああ" | 9byte | Success |
| "ああああ" | 12byte | Success |
| "ああああa" | 13byte | Failed |
| "あああああ" | 15byte | Failed |

**Success File**
```ruby
class Foo
  # ああああ
  def foobar
    puts 'foobar'
  end
end

foo = Foo.new
foo.foobar
``` 

**Failed File**
```ruby
class Foo
  # あああああ
  def foobar
    puts 'foobar'
  end
end

foo = Foo.new
foo.foobar
``` 

### environment
- macOS Sonoma 14.4 
- ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
- About VSCode
  - Version: 1.93.1 (Universal)
  - Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
  - Date: 2024-09-11T17:20:05.685Z
  - Electron: 30.4.0
  - ElectronBuildId: 10073054
  - Chromium: 124.0.6367.243
  - Node.js: 20.15.1
  - V8: 12.4.254.20-electron.0
  - OS: Darwin arm64 23.4.0

**Comment by vinistock** [comment] 2024-09-25 14:23
Since this issue is a duplicate of #1251, I'm going to close this issue to centralize all discussions there. PR #2619 is about to fix this.

**Closed as not planned by vinistock** 2024-09-25 14:23 UTC
Labels: bug, pinned
