### ISSUE TITLE
Support for Neovim

### ISSUE THREAD

**Issue by pBorak** [Shopify/ruby-lsp#188] opened 2022-07-07 07:53 UTC
Let me start by saying I am so excited that ruby tooling has gotten some love lately.
Are there a plans to add support for other editors (most notably) Neovim?
Neovim since version 0.5 natively [supports](https://neovim.io/doc/lsp/) Language Server Protocol and there is a significant subset of already supported [LSP](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md).

**Comment by alexwu** [comment] 2022-07-08 17:25
I just wanted to hop in and drop my `neovim` config that I've been using for a little while:

```
local lspconfig = require("lspconfig")
local configs = require("lspconfig.configs")
local util = require("lspconfig.util")

if not configs.ruby_lsp then
	local enabled_features = {
		"documentHighlights",
		"documentSymbols",
		"foldingRanges",
		"selectionRanges",
		-- "semanticHighlighting",
		"formatting",
		"codeActions",
	}

	configs.ruby_lsp = {
		default_config = {
			cmd = { "ruby-lsp" },
			filetypes = { "ruby" },
			root_dir = util.root_pattern("Gemfile", ".git"),
			init_options = {
				enabledFeatures = enabled_features,
			},
			settings = {},
		},
		commands = {
			FormatRuby = {
				function()
					vim.lsp.buf.format({
						name = "ruby_lsp",
						async = true,
					})
				end,
				description = "Format using ruby-lsp",
			},
		},
	}
end

lspconfig.ruby_lsp.setup({ on_attach = on_attach, capabilities = capabilities })
```

I hope this helps!

**Comment by vinistock** [comment] 2022-07-08 19:06
If you use it without bundler and your app has `RuboCop` extensions (e.g.: `rubocop-performance`), it will fail when trying to require them.

We are going to explore allowing the Ruby LSP to be executed without bundler, but then it'll probably fall back to formatting files using SyntaxTree and disable all RuboCop functionality.

**Comment by alexventuraio** [comment] 2022-08-15 16:51
To try this, I just need to install the `ruby-lsp` gem and where should I put @alexwu config?

**Comment by vinistock** [comment] 2022-08-16 13:48
While our team's focus is on supporting VS Code, we'd gladly add an `EDITOR_SETUP.md` file linked from the README with community driven instructions on how to get the Ruby LSP working on other editors.

Would that be helpful? We could get started with neovim.

**Comment by wassimk** [comment] 2022-08-16 14:16
@vinistock yes, I think that would be helpful. I have a branch adding ruby-lsp to the nvim-lspconfig project. Once that goes through I'll be happy to write some Neovim instructions.

**Comment by alexventuraio** [comment] 2022-08-16 22:57
@wassimk thanks for sharing your solution, I'm looking forward to go through your PR and read your instructions to get it done.

**Comment by cj** [comment] 2022-09-29 21:09
@alexwu thank you for your config, it worked great. I did notice one issue, diagnostics errors do not show.

**Comment by alexwu** [comment] 2022-09-30 21:46
@cj @wassimk Darn, I've been a bit behind on `ruby-lsp` versions of late, so I didn't know about this. 

I'll see if there's any info on `neovim` supporting that spec when I get the chance.

**Comment by jameswritescode** [comment] 2022-10-05 20:24
neovim does not support `textDocument/diagnostic` with no official plans to support it

from matrix:

```
   newton | are there any plans to support textDocument/diagnostic to request diagnostics from LSP?
gpanders_ | no current plans, but that does not mean a PR implementing that support would be rejected
```

**Comment by technicalpickles** [comment] 2022-11-22 18:06
It looks like lspconfig now ships with support directly: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ruby_ls

**Comment by technicalpickles** [comment] 2022-12-02 16:32
One downside I'm seeing for using the lsp is that you'll see an error about connecting to the LSP when the `Gemfile` doesn't have it. I'm not sure if there's a way to have a callback to determine that 🤔

**Comment by technicalpickles** [comment] 2023-02-15 15:43
> One downside I'm seeing for using the lsp is that you'll see an error about connecting to the LSP when the Gemfile doesn't have it. I'm not sure if there's a way to have a callback to determine that 

I found a way to do this 🎉  I was looking at adding `on_new_config`, but in looking for options I came across https://github.com/neovim/nvim-lspconfig/issues/1886 and  https://github.com/mihyaeru21/nvim-lspconfig-bundler . Confirmed the plugin runs through bundler 🎉

**Comment by vinistock** [comment] 2023-03-06 20:38
Folks, I added an [editors](https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md) file to aggregate configurations for the Ruby LSP in editors other than VS Code. If somebody wants to contribute instructions for NeoVim, we can put it there and close this issue.

We can also include multiple alternatives if there's not a single way of doing it.

**Comment by smarquez1** [comment] 2023-03-31 15:31
Link to related neovim and nvim-lspconfig issues:
* https://github.com/neovim/nvim-lspconfig/pull/2498
* https://github.com/neovim/neovim/issues/22838

**Comment by vinistock** [comment] 2023-03-31 15:46
Another thing that might help: since #562, we switched features from being opt-in to being opt-out so that configuration is easier for editors (everything is enabled by default if no config is passed).

**Comment by b-sep** [comment] 2023-04-29 15:04
Any help? This is my config

```lua
if server == 'ruby_ls' then
  if not configs.ruby_lsp then
    local enabled_features = {
      "documentHighlights",
      "documentSymbols",
      "foldingRanges",
      "selectionRanges",
      "semanticHighlighting",
      "formatting",
      "codeActions",
    }

    configs.ruby_lsp = {
      default_config = {
        cmd = { "bundle", "exec", "ruby-lsp" },
        filetypes = { "ruby" },
        root_dir = util.root_pattern("Gemfile", ".git"),
        init_options = {
          enabledFeatures = enabled_features,
        },
        settings = {},
      },
      commands = {
        FormatRuby = {
          function()
            vim.lsp.buf.format({
              name = "ruby_lsp",
              async = true,
            })
          end,
        description = "Format using ruby-lsp",
        },
      },
    }
  end
end
```

gem is installed but despite server attached, im keep getting this error

![Screenshot from 2023-04-29 12-03-40](https://user-images.githubusercontent.com/65205717/235309594-761d5eb5-a2a7-493a-8091-81372b5e4d12.png)
![Screenshot from 2023-04-29 12-03-57](https://user-images.githubusercontent.com/65205717/235309596-42fca0e6-dbc6-43a9-8c93-c51d33bcf858.png)

**Comment by b-sep** [comment] 2023-04-29 18:02
any help?

`lsp_config.lua`
```lua
local status_ok, lspconfig = pcall(require, 'lspconfig')
if not status_ok then
  return
end

local servers = require("junior.lsp.servers")

for _, server in pairs(servers) do
  local opts = {}
  local handler = require("junior.lsp.handlers")

  opts = {
    on_attach = handler.on_attach,
    capabilities = handler.capabilities,
  }

  if server == 'lua_ls' then
    opts = vim.tbl_deep_extend("force", {
      settings = {
        Lua = {
          diagnostics = {
            globals = { "vim" },
          },
        },
      },
    }, opts)
  end

  lspconfig[server].setup(opts)
end
```

`servers.lua`
```lua
local servers = {
  'lua_ls',
  'tsserver',
  'ruby_ls'
}

return servers
```

When i open a buffer with ruby file, i can see the the ruby_ls has attached to the buffer but i dont get any completion or diagnostic. I already tried the suggestions on this issue and nothing happens. Im have the gem installed btw.

![image](https://user-images.githubusercontent.com/65205717/235317386-e5538a29-459f-4405-820b-1b7cfdb3025d.png)

on the LspLog i have this [ERROR] but i dont know what this means

![image](https://user-images.githubusercontent.com/65205717/235317428-72308e65-bd40-4b7b-98c7-15d0573efd53.png)

**Comment by cefigueiredo** [comment] 2023-04-30 05:18
@b-sep We can not see the handler where you customize the on-attach. 
But probably it's missing the workaround to make neovim send diagnostic requests to ruby-lsp as suggested on a prior comment, and detailed here neovim/nvim-lspconfig#2498

**Comment by technicalpickles** [comment] 2023-05-03 13:35
I'm not sure if this is neovim specific, or a broader ruby-lsp question: if you use sorbet, is there any guidance/recommendations for using the sorbet LSP and ruby-lsp together? There is definitely some overlap as noted in https://github.com/Shopify/ruby-lsp/issues/206

I'm still learning and  understanding nvim + lsp, but I get the impression only one ruby LSP ends up being attached.

**Comment by vinistock** [comment] 2023-05-03 13:41
The default behaviour for language servers is to allow for more than one and merge responses. If both the Ruby LSP and Sorbet implement the same request, you'd just get the results duplicated in the editor.

We use both Sorbet and the Ruby LSP on our projects (even on the Ruby LSP project itself, we use both). This works out of the box on VS Code, but I have no idea how NeoVim handles it.

**Comment by technicalpickles** [comment] 2023-05-04 13:53
I posted this over on @cefigueiredo's https://github.com/neovim/nvim-lspconfig/pull/2498 , but figured would share here too:

> Would it be reasonable to just added the recommended workaround to lua/lspconfig/server_configurations/ruby_ls.lua rather than documenting the workaround? That way, users get a better out of box experience until there is support in neovim itself.
> 
> I can think of a few ways to detect the older versions, but they are kinda dirty. ruby-lsp doesn't have a --version flag unfortunately. It would be in someone's Gemfile.lock if they have it for their project, but that isn't always how it's installed.
> 
> Maybe an option to work for new vs old ruby-lsp?

I'm just trying to work out what the easiest way to enable vim folks to use ruby-lsp without needing much extra configuration. I think it's moving the workaround into nvim-lspconfig, or maybe another package?

Is there anything that can be implemented within ruby-lsp?

**Comment by metalelf0** [comment] 2023-07-10 05:56
I'm trying to set ruby-lsp up in my neovim config. The gem is installed correctly and it seems to start fine. When I enter any ruby file, though, I get this error in the `LspLog`:

```
LSP[ruby_ls]: Error INVALID_SERVER_MESSAGE: {
  jsonrpc = "2.0"
}
```

I don't think I have anything fancy set up, just the usual `nvim-lspconfig` stuff + mason and diagnostics, but from the error it looks like neovim is not even "establishing a communication" with the LSP, right?

I tried searching online but I have literally no clue about where to start to address this issue.

Any clue about what I might be missing / doing wrong? My dot files are here: 

https://github.com/metalelf0/dot-files/tree/master/.config/nvim

Thanks in advance!

**Comment by atishdhu** [comment] 2023-07-15 06:53
## Problem
I am using NvChad with the following **`lspconfig`** for **`ruby_ls`**.
```lua
lspconfig.ruby_ls.setup {
  on_attach = function(client, buffer)
    local callback = function()
      local params = vim.lsp.util.make_text_document_params(buffer)
  
      client.request(
        'textDocument/diagnostic',
        { textDocument = params },
        function(err, result)
          if err then return end
  
          vim.lsp.diagnostic.on_publish_diagnostics(
            nil,
            vim.tbl_extend('keep', params, { diagnostics = result.items }),
            { client_id = client.id }
          )
        end
      )
    end
  
    callback() -- call on attach
  
    vim.api.nvim_create_autocmd({ 'BufEnter', 'BufWritePre', 'BufReadPost', 'InsertLeave', 'TextChanged' }, {
      buffer = buffer,
      callback = callback,
    })
  end,
  capabilities = capabilities,
}
```

I added the workaround to make diagnostics work in neovim but there is an error when i make a change in a `.rb` file:

```text
Error executing vim.schedule lua callback: /home/adhu/.config/nvim/lua/custom/configs/lspconfig.lua:67: attempt to index local 'result' (a nil value)
```

## `:LspInfo`
![image](https://github.com/Shopify/ruby-lsp/assets/56167292/2bfdf556-3948-467e-9d7e-7932ef403332)

**Closed** 2023-07-24 15:00 UTC

**Comment by staycreativedesign** [comment] 2024-01-28 05:02
> I just wanted to hop in and drop my `neovim` config that I've been using for a little while:
> 
> ```
> local lspconfig = require("lspconfig")
> local configs = require("lspconfig.configs")
> local util = require("lspconfig.util")
> 
> if not configs.ruby_lsp then
> 	local enabled_features = {
> 		"documentHighlights",
> 		"documentSymbols",
> 		"foldingRanges",
> 		"selectionRanges",
> 		-- "semanticHighlighting",
> 		"formatting",
> 		"codeActions",
> 	}
> 
> 	configs.ruby_lsp = {
> 		default_config = {
> 			cmd = { "bundle", "exec", "ruby-lsp" },
> 			filetypes = { "ruby" },
> 			root_dir = util.root_pattern("Gemfile", ".git"),
> 			init_options = {
> 				enabledFeatures = enabled_features,
> 			},
> 			settings = {},
> 		},
> 		commands = {
> 			FormatRuby = {
> 				function()
> 					vim.lsp.buf.format({
> 						name = "ruby_lsp",
> 						async = true,
> 					})
> 				end,
> 				description = "Format using ruby-lsp",
> 			},
> 		},
> 	}
> end
> 
> lspconfig.ruby_lsp.setup({ on_attach = on_attach, capabilities = capabilities })
> ```
> 
> I hope this helps!

How would I lazy load this using return { } ?

**Comment by simonbernard-shopify** [comment] 2024-06-11 15:47
> > I just wanted to hop in and drop my `neovim` config that I've been using for a little while:
> > ```
> > local lspconfig = require("lspconfig")
> > local configs = require("lspconfig.configs")
> > local util = require("lspconfig.util")
> > 
> > if not configs.ruby_lsp then
> > 	local enabled_features = {
> > 		"documentHighlights",
> > 		"documentSymbols",
> > 		"foldingRanges",
> > 		"selectionRanges",
> > 		-- "semanticHighlighting",
> > 		"formatting",
> > 		"codeActions",
> > 	}
> > 
> > 	configs.ruby_lsp = {
> > 		default_config = {
> > 			cmd = { "bundle", "exec", "ruby-lsp" },
> > 			filetypes = { "ruby" },
> > 			root_dir = util.root_pattern("Gemfile", ".git"),
> > 			init_options = {
> > 				enabledFeatures = enabled_features,
> > 			},
> > 			settings = {},
> > 		},
> > 		commands = {
> > 			FormatRuby = {
> > 				function()
> > 					vim.lsp.buf.format({
> > 						name = "ruby_lsp",
> > 						async = true,
> > 					})
> > 				end,
> > 				description = "Format using ruby-lsp",
> > 			},
> > 		},
> > 	}
> > end
> > 
> > lspconfig.ruby_lsp.setup({ on_attach = on_attach, capabilities = capabilities })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this helps!
> 
> How would I lazy load this using return { } ?

Bump :)

**Comment by wassimk** [comment] 2024-06-11 16:01
> How would I lazy load this using return { } ?

I need help understanding the question. The LSP will only start in Ruby files. That should be the required lazy loading.
