### ISSUE TITLE
Failed to activate Ruby environment: spawn /bin/sh ENOENT

### ISSUE THREAD

**Issue by CermakM** [Shopify/ruby-lsp#1887] opened 2024-04-05 06:13 UTC
### Description

Hi!

I am new to ruby and I am trying to run ruby-lsp in VSCode. However, I am unable to do that, ending up with the following error:

![Screenshot 2024-04-05 at 8 07 16](https://github.com/Shopify/ruby-lsp/assets/22003700/f139959e-a25c-49ed-b055-31558405d31a)

I am pretty sure my SHELL env is set to `/bin/zsh`. I tried checking the codebase and executing 
```
/bin/zsh -ic 'rbenv exec ruby -rjson -e "puts JSON.dump(ENV.to_h)"'
```

the `SHELL` is set correctly.

I have `.ruby-version` file in the repo containing `3.3.0`.

When running `ruby-lsp` in the terminal, I am not sure if the output is correct:

```
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
Resolving dependencies...
The Gemfile's dependencies are satisfied
```

Even when waiting for quite some time, this is the only output I get.

BIG thanks for any help! ❤️ 

### Reproduction steps

The only thing I did is installing rbenv and installing the ruby-lsp VScode extension.

I am running the latest version of VScode on MacOS M3. Tried to switch even to the pre-release version of the extension but the issue stays the same.

**Code snippet or error message**
```ruby
Failed to activate rbenv environment: spawn /bin/sh ENOENT
```

**Comment by thuandohoang** [comment] 2024-04-07 06:56
I also got the same issue. After I install an older version (0.2.2), and then reinstall the newest one, the issue has gone.

**Comment by CermakM** [comment] 2024-04-11 23:01
@thuandohoang That's interesting! I downgraded it to 0.2.2 and it indeed works! However, when I upgrade it back, I get a different issue when starting Ruby LSP 😆  🤷 

```
Cannot create property 'identifier' on string 'asdf'
```

**Comment by gottlike** [comment] 2024-04-12 13:43
If I just delete this line, it works again!

**Comment by vinistock** [comment] 2024-04-12 17:20
The new error is a bug in the latest version, which will be fixed by https://github.com/Shopify/ruby-lsp/pull/1923 and not related in any way to the original issue.

@CermakM are there any logs in the `output` tab under the `Ruby LSP` channel?

**Comment by vinistock** [comment] 2024-05-30 21:08
Closing this for now. If the issue is still occurring in v0.7.1, please let us know.

**Closed by vinistock** 2024-05-30 21:08 UTC
Labels: bug
