### ISSUE TITLE
VScode "Ruby LSP: Start" throws "./Gemfile -W0 -rjson -e 'STDER...: Permission denied"

### ISSUE THREAD

**Issue by Ryazbeck** [Shopify/ruby-lsp#2400] opened 2024-08-01 16:06 UTC
### Description

MacOS, 2021 macbook, sonoma 14.6
ruby 3.3.3, asdf, VScode Version: 1.91.1, 

1. From VScode command palate run "Ruby LSP: Start"
2. Error:
```
Command failed: /Users/<me>/<path>/<to>/<project>/Gemfile -W0 -rjson -e 'STDERR.print({ env: ENV.to_h, yjit: !!defined?(RubyVM::YJIT), version: RUBY_VERSION }.to_json)'
/bin/sh: /Users/<me>/<path>/<to>/<project>/Gemfile: Permission denied
```
4. Gem uninstall ruby-lsp and ruby-lsp-server
5. Uninstall all ruby and rails extensions from VScode 
7. Update `asdf` per ruby-lsp troubleshooting
8. Restart VScode
6. Install only ruby-lsp extension in VScode
9. Set ruby-lsp version manager to `asdf`
10. Restart VScode
11. Same error
12. I also see in vscode Output for ruby-lsp that it wants a ruby version, so i set custom ruby version command to `asdf install ruby 3.3.3`
13. Set version manager to asdf
14. Error is logged in output that asdf is not found
15. Also getting same permission denied error from above

---

1. "Install Another Version" of ruby-lsp  VScode extension back to `v0.5.20`
2. Set ruby-lsp version manager to custom
```
"rubyLsp.rubyVersionManager": {
  "identifier": "custom"
},
```
4. Remove custom ruby version command
5. restart extensions
6. Now it works
```
2024-08-01 11:00:22.987 [info] (platform) Ruby LSP> Skipping custom bundle setup since /<path>/.ruby-lsp/Gemfile.lock already exists and is up to date

2024-08-01 11:00:23.009 [info] (platform) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2

2024-08-01 11:00:23.695 [info] (platform) The Gemfile's dependencies are satisfied

2024-08-01 11:00:24.686 [info] (platform) Initializing Ruby LSP v0.17.10...

2024-08-01 11:00:24.768 [info] (platform) Finished initializing Ruby LSP!

2024-08-01 11:00:24.826 [info] (platform) [Standard Ruby] Activating Standard Ruby LSP addon v1.39.2

2024-08-01 11:00:25.215 [info] (platform) [Standard Ruby] Initialized Standard Ruby LSP addon 1.39.2

2024-08-01 11:00:25.216 [info] (platform) Activating Ruby LSP Rails addon v0.3.11

2024-08-01 11:00:25.223 [info] (platform) Ruby LSP Rails booting server

2024-08-01 11:00:32.833 [info] (platform) Finished booting Ruby LSP Rails server
```

**Comment by vinistock** [comment] 2024-09-13 20:35
Thank you for the bug report.

Based on this line

```
/Users/<me>/<path>/<to>/<project>/Gemfile -W0 -rjson -e 'STDERR.print({ env: ENV.to_h, yjit: !!defined?(RubyVM::YJIT), version: RUBY_VERSION }.to_json)'
```

It seems like it might be a misconfiguration of the custom activation command. Everything starting on `-W0` are arguments to the `ruby` command, but instead you have the path to a `Gemfile` in there.

The extension never invokes uses a `Gemfile` path to invoke that command, so I don't believe it's a bug in the code. Could it be that the path to the `Gemfile` was intended for the `bundleGemfile` setting instead of the custom activation script?

I'm closing the issue for now, but if you find that what I mentioned isn't the case and bug persists, please let us know.

**Closed by vinistock** 2024-09-13 20:35 UTC
Labels: bug

**Comment by Ryazbeck** [comment] 2025-03-03 23:06
Hi, @vinistock I finally figured this out with the help of my colleagues. 

VSCode caches settings locally in `~/Library/Application Support/Code/User/globalStorage`, which you can read about [here](https://medium.com/@krithikanithyanandam/vs-code-extension-storage-explained-the-what-where-and-how-3a0846a632ea)

So we first tried the RubyLSP command palette to get "clear previous workspace selection", but for some reason it wouldn't appear in my VSCode.

Settings variable suspecte to store the faulty Gemfile path [here](https://github.com/Shopify/ruby-lsp/blob/0a4fbda00ebff6f860f0261ff263e0cc9d097245/vscode/src/ruby.ts#L226-L229). 

So I went into extension.js in `async activateRuby` and added a line that shows this setting is returning that Gemfile path even though I have removed all rubyLsp settings from my settings.json (User and Workspace), reinstalled RubyLSP and reloaded VSCode many times over the last several months since I opened this issue.

```
let t = this.context.workspaceState.get(`rubyLsp.workspaceRubyPath.${this.workspaceFolder.name}`);
this.outputChannel.info(`Activating Ruby with ${t}`);

output:
2025-03-03 16:10:14.822 [info] (platform) Activating Ruby with /Users/russellyazbeck/projects/<project>/Gemfile
```

I put this line in before `t` 

```
this.context.workspaceState.update(`rubyLsp.workspaceRubyPath.${this.workspaceFolder.name}`, undefined)
```

And now it works! Must be a VSCode caching issue. Not sure how to ensure it doesn't happen again, but at least RubyLSP VSCode extension is working on the latest version for me.

**Comment by vinistock** [comment] 2025-03-03 23:42
Thank you for sharing what the root cause was. I guess we could enforce that, when offering manual Ruby fallbacks, the selected file must be an executable named `ruby`. And maybe offer the command to clear the workspace state cache directly from the command palette.

Do you think that would be helpful?

**Comment by Ryazbeck** [comment] 2025-03-03 23:47
Yeah that sounds like a great solution, thank you!
