### ISSUE TITLE
Format on save is not working.

### ISSUE THREAD

**Issue by thibgn** [Shopify/ruby-lsp#1141] opened 2023-10-25 08:23 UTC
### Operating System

Mac OS 13.0

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

I'm having a few issues with Ruby LSP that I can't seem to fix.

First, the indexing is stuck at 0%. 
No matter how long I wait, the settings I use, I never see anything else than `Ruby LSP: indexing files: 0% completed`

But the main issue is the **formatting that doesn't work on save** (it _kinda_ works when I format manually, but it only fixes indentation).

I obviously checked my VSCode configuration and nothing should prevent the format on save (it's working for other languages).

Here's the relevant settings I use for ruby : 
```json
  "rubyLsp.rubyVersionManager": "rbenv",
  "[ruby]": {
	"editor.defaultFormatter": "Shopify.ruby-lsp",
	"editor.formatOnSave": true,
	"editor.formatOnType": true,
	"editor.tabSize": 2,
	"editor.insertSpaces": true,
	"files.trimTrailingWhitespace": true,
	"files.insertFinalNewline": true,
	"files.trimFinalNewlines": true,
	"editor.rulers": [120],
	"editor.semanticHighlighting.enabled": true
  },
```

I noticed I had both `rvm` & `rbenv` installed so I removed rvm and made sure rbenv was [properly configured](https://github.com/rbenv/rbenv#basic-git-checkout).
I also made sure `$SHELL` was available : i'm using `zsh` so its value is `/bin/zsh`

I also removed everything ruby or rails related in my VScode extensions.

Here's the logs from Ruby LSP : 
```
Ruby LSP> Skipping custom bundle setup since /Users/thib/code/myproject/api/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
The Gemfile's dependencies are satisfied
Starting Ruby LSP...
```

Also, in the Output tab, `Window` is logging the following which may be related ? 

```
2023-10-25 10:01:00.488 [error] [Extension Host] Received response message without id: Error is: 
{
    "code": -32603,
    "message": "#<NoMethodError: undefined method `dependencies' for nil:NilClass>",
    "data": {
        "errorClass": "NoMethodError",
        "errorMessage": "undefined method `dependencies' for nil:NilClass",
        "backtrace": "~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:197:in `block in initial_excluded_gems'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:194:in `each'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:194:in `initial_excluded_gems'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:21:in `initialize'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/ruby_indexer.rb:20:in `new'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/ruby_indexer.rb:20:in `configuration'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/visitor.rb:248:in `block in collect_comments'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/visitor.rb:243:in `downto'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/visitor.rb:243:in `collect_comments'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `bind_call'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/visitor.rb:222:in `add_class_entry'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `bind_call'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/visitor.rb:25:in `visit_class_node'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `bind_call'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/node.rb:2876:in `accept'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `block in visit_child_nodes'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `each'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `visit_child_nodes'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/node.rb:14835:in `accept'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `block in visit_child_nodes'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `each'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `visit_child_nodes'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/prism-0.15.1/lib/prism/node.rb:12985:in `accept'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_indexer/lib/ruby_indexer/index.rb:184:in `index_single'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `bind_call'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/executor.rb:198:in `block in did_change_watched_files'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/executor.rb:184:in `each'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/executor.rb:184:in `did_change_watched_files'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `bind_call'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/executor.rb:172:in `run'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/executor.rb:26:in `execute'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/server.rb:135:in `block (2 levels) in new_worker'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/server.rb:123:in `loop'\n~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.0/lib/ruby_lsp/server.rb:123:in `block in new_worker'"
    }
}
```

That's about it, let me know if I can provide anything else :)

**Comment by vinistock** [comment] 2023-10-25 15:06
I noticed a concurrency issue from your backtrace, which I addressed in the linked PR. I'm not 100% sure it'll fix the issue yet, but let's give it a try and revisit.

**Comment by thibgn** [comment] 2023-10-26 10:12
Oh well, the fresh install solved everything.
Indexing now works properly, as well as the formatting on save.

Bad news is that we'll never know what caused this in the first place 🤷 

I'm closing this, thanks for the help !

**Comment by vinistock** [comment] 2023-10-26 19:58
Okay, I dig a bit into the rubygems code again to try to understand the root cause. I suspect this is [the step](https://github.com/rubygems/rubygems/blob/1a1948424aca90013b37cb8a78f5d1d5576023f1/lib/rubygems/dependency.rb#L333) that's causing `to_spec` to return `nil`.

You said removing `rubocop-rails` fixes the issue. Can you share which version of `rubocop-rails` your project is locked to? And what is your Gemfile requirement constraints? Is it a prerelease version by any chance?

On that line I shared, rubygems takes all specs with prereleases and tries to place them at the end of the list. But it only does so if the `requirement` matches. If it doesn't, then `matches` will be an empty array and the method will return `nil`.

**Comment by thibgn** [comment] 2023-10-26 20:32
>  Can you share which version of `rubocop-rails` your project is locked to? And what is your Gemfile requirement constraints? Is it a prerelease version by any chance?

In my Gemfile.lock I found `rubocop-rails (2.21.2)`.
In my Gemfile I only have `gem 'rubocop-rails', require: false`.

I'm not sure about the prerelease, does the above information clears that up ?

**Comment by ansonhoyt** [comment] 2023-10-26 20:34
Running your checks https://github.com/Shopify/ruby-lsp/issues/1141#issuecomment-1779296146 in irb, I have one pre-release dependency and `rubocop-rails` 2.21.2.

```ruby
# Print the name of all dependencies where `to_spec` returns `nil`
puts dependencies.select { |d| d.to_spec.nil? }.map(&:name)
# nil

puts dependencies.select { |d| d.to_spec.version.prerelease? }
# rails (~> 7.1.0.beta1)

puts Gem::Specification.find_by_name('rails').version
# 7.1.0.rc2

puts Gem::Specification.find_by_name('rubocop-rails').version
# 2.21.2
```

**Comment by ansonhoyt** [comment] 2023-10-26 21:24
With a little `puts` debugging, I found the nil `to_spec`:

```diff
# /Users/ahoyt/.rvm/gems/ruby-3.2.2@caboose/gems/ruby-lsp-0.12.1/lib/ruby_indexer/lib/ruby_indexer/configuration.rb
+       warn("HACK> #{dependency}") if dependency.to_spec.nil?
        dependency.to_spec.dependencies.each do |transitive_dependency|
```

Gives:

```txt
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
HACK> activemodel (>= 6.0.0)
/Users/ahoyt/.rvm/gems/ruby-3.2.2@caboose/gems/ruby-lsp-0.12.1/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:202:in `block in initial_excluded_gems': undefined method `dependencies' for nil:NilClass (NoMethodError)

        dependency.to_spec.dependencies.each do |transitive_dependency|
                          ^^^^^^^^^^^^^
```

**Comment by ansonhoyt** [comment] 2023-10-26 22:11
Ok, so I tried to list more than just the first one...

```diff
# /Users/ahoyt/.rvm/gems/ruby-3.2.2@caboose/gems/ruby-lsp-0.12.1/lib/ruby_indexer/lib/ruby_indexer/configuration.rb
+        warn("HACK> #{dependency.inspect}") if dependency.to_spec.nil?
+        dependency&.to_spec&.dependencies.then{Array(_1)}.each do |transitive_dependency|
-        dependency.to_spec.dependencies.each do |transitive_dependency|
```

Which worked...and let Ruby LSP finish loading 😄 

```txt
Ruby LSP> Command: (bundle check || bundle install) 1>&2
Resolving dependencies...
The Gemfile's dependencies are satisfied
HACK> <Gem::Dependency type=:runtime name="activemodel" requirements=">= 6.0.0">
HACK> <Gem::Dependency type=:runtime name="actionview" requirements=">= 6.0.0">
HACK> <Gem::Dependency type=:runtime name="activerecord" requirements=">= 4.2">
Starting Ruby LSP...
Ruby LSP is ready
```

I have no idea what that means 🤷 but you probably do! 👍

**Closed** 2023-10-31 18:51 UTC
Labels: bug

**Comment by homezada** [comment] 2023-11-03 19:12
I get errors when starting ruby-lsp and it seems related to this issue? I have 0.12.2 but needed to add the following additional nil checks to #1159 for it to start correctly.

ruby-lsp-0.12.2 lib/ruby_indexer/configuration.rb

190      this_gem = Bundler.definition.dependencies.find do |d|
191        d.to_spec.full_gem_path == Dir.pwd **if !d.to_spec.nil? && d.to_spec.respond_to?(:full_gem_path)**
192      rescue Gem::MissingSpecError


209          # If the transitive dependency is included as a transitive dependency of a gem outside of the development
210          # group, skip it
211          next if others.any? { |d| **!d.to_spec.nil? &&** d.to_spec.dependencies.include?(transitive_dependency) }

Updated 191 & 211 as would get NoMethod on nil to_spec.

**Comment by Skulli** [comment] 2023-11-25 12:40
Not sure if thats 100% related, but i am getting startup error on another project

    /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:196:in `block in initial_excluded_gems': undefined method `full_gem_path' for nil:NilClass (NoMethodError)

        d.to_spec.full_gem_path == Dir.pwd
                 ^^^^^^^^^^^^^^
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:195:in `each'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:195:in `find'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:195:in `initial_excluded_gems'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/lib/ruby_indexer/configuration.rb:21:in `initialize'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/ruby_indexer.rb:15:in `new'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/ruby_indexer.rb:15:in `<module:RubyIndexer>'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_indexer/ruby_indexer.rb:14:in `<top (required)>'
	from <internal:/home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/lib/ruby_lsp/internal.rb:19:in `<top (required)>'
	from <internal:/home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.12.5/exe/ruby-lsp:89:in `<top (required)>'
	from /home/user/.rbenv/versions/3.2.2/bin/ruby-lsp:25:in `load'
	from /home/user/.rbenv/versions/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
	from /home/user/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /home/user/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

    2023-11-25 13:32:05.873 [info] [Error - 13:32:05] Server process exited with code 1.
    2023-11-25 13:32:05.873 [info] [Error - 13:32:05] Server initialization failed.

latest bundler/gem is installed.
When i call the dependencies code from above, i get the error

    Gem::MissingSpecError: Could not find 'tzinfo-data' (>= 0) among 245 total gem(s)

**Comment by Skulli** [comment] 2023-11-30 14:54
I found the line in my Gemfile, it is

    gem "capistrano3-puma", "> 5", require: false

if i comment out that line, ruby-lsp is booting.

**Comment by SleeplessByte** [comment] 2024-01-06 20:54
https://github.com/Shopify/ruby-lsp/blob/eb0e725c32691015536a91a3b525ea2f70090952/lib/ruby_indexer/lib/ruby_indexer/configuration.rb#L216

This line still triggers when bundling a custom gem with a transitive dependency that lacks a spec.

**Comment by thibgn** [comment] 2024-02-09 10:34
Hello, it's me again.

I'm having a hard time with `Ruby LSP` and after numerous VSC reinstallations I figured I'd bump this issue to try and get some help.

Basically the formatting doesn't work, neither on save nor manually. Usually after a clean VSC reinstallation it works for a while but then stops for some reason. Lately I noticed a trend on the saving of files taking ages :

![image](https://github.com/Shopify/ruby-lsp/assets/56600224/dd3e24b3-2d8f-45bb-8538-bc6b70e9f3d8)

I discovered `Start Extension Bisect` (pretty useful!) but that didn't solve anything. I disabled every extension I had and still can't make the formatting work on my ruby files (whatever the project I'm in).

I don't have anything suspicious on the `Ruby LSP` output : 

![image](https://github.com/Shopify/ruby-lsp/assets/56600224/9cf427e8-d48d-4b75-99da-9777e72c5281)

I do have this warning in the Extension host though : `[warning] Shopify.ruby-lsp - Code actions of kind 'source.fixAll.eslint 'requested but returned code action is of kind 'refactor.extract'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
`

But I'm not sure on how to interpret this.

Anyway, help would be much appreciated, let me know what else I can provide to try and fix this.

Cheers
