### ISSUE TITLE
unexpected local variable or method diagnostic in erb when multiple ruby fragments on the same line

### ISSUE THREAD

**Issue by mbriggs** [Shopify/ruby-lsp#2448] opened 2024-08-15 11:49 UTC
### Description

On Neovim v0.10.1 going through lspconfig/mason with ruby-lsp v0.17.13

### Reproduction steps

Given erb with multiple ruby fragments on the same line, the diagnostic "unexpected local variable or method" shows up when it should not. If you add a line break in the source, it goes away. If you remove the line break, it comes back. 

The expectation should be that each fragment is distinct.

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/11f38d00-352d-4e0d-94d7-6f012861ef12">
Note that the first example has line breaks and no diagnostics

**Comment by st0012** [comment] 2024-08-15 12:03
Does applying the configs from https://github.com/Shopify/ruby-lsp/pull/2432#issuecomment-2288847806 solve the issue?

**Comment by st0012** [comment] 2024-08-15 12:36
Yeah sorry, please ignore that.
I can't reproduce this issue in VS Code though. The diagnostics feature should also be disabled for erb files anyway. Can you check with folks in #2432 to see if they have similar issues?

**Comment by vinistock** [comment] 2024-08-28 16:37
Closing this as there's no fix from the Ruby LSP side.

**Closed as completed by vinistock** 2024-08-28 16:37 UTC
Labels: bug
