### ISSUE TITLE
Auto complete doesn't work if I write code under the ASCII logo

### ISSUE THREAD

**Issue by motebaya** [Shopify/ruby-lsp#2345] opened 2024-07-23 14:43 UTC
### Description

at first, i thought it was because of the heredoc, so i changed the logo to a single line, but the auto complete still doesn't work. 
it's weird, why would an ASCII logo which should be read as a regular string, affect autocomplete?

https://github.com/user-attachments/assets/e76a0af8-0519-45bc-bcc2-3b9e3416df42

LSP configuration:
![Screenshot from 2024-07-23 20-56-05](https://github.com/user-attachments/assets/72ca3d6a-01c7-4b0b-8238-2bcf27db42d3)

ASCII logo generated from: https://patorjk.com/software/taag/#p=display&f=Calvin%20S&t=LoGOs

**Comment by vinistock** [comment] 2024-07-23 14:50
Thank you for the report!

The issue is related to multibyte characters. Since we already have an issue for it (https://github.com/Shopify/ruby-lsp/issues/1251), I'll close this one to centralize the discussions in a single place.

The summary is that VS Code deals with locations in terms of code units and not bytes or characters. We started out focusing on support for ASCII only text because it's both easier to support, but also has much better performance (handling multibyte characters is expensive).

**Closed by vinistock** 2024-07-23 14:50 UTC
Labels: bug
