### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by filiptronicek** [Shopify/ruby-lsp#1092] opened 2023-10-13 14:10 UTC
Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or the redistribution of `.vsix` files from it, in order to use the LSP in non-Microsoft products, it would be awesome if the team takes ownership of the extension namespace on [Open VSX](https://open-vsx.org/) and publishes this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

I would love to help wherever I can with this, so please do reach out. This extension is now the preferred alternative to the now deprecated `wingrunr21.vscode-ruby` extension, so would be great to have a newer alternative available/

**Comment by vinistock** [comment] 2023-10-13 14:30
Thank you for the suggestion! This is a duplicate of https://github.com/Shopify/vscode-ruby-lsp/issues/401.

We're finishing up some licensing reviews and will then add automation to publish it to Open VSX.

**Closed by vinistock** 2023-10-13 14:30 UTC
